# This rule is not used by the project config-to-deploy itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the cfg2deploy.meng.xu.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: config-to-deploy
    app.kubernetes.io/managed-by: kustomize
  name: configdeployment-editor-role
rules:
- apiGroups:
  - cfg2deploy.meng.xu
  resources:
  - configdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cfg2deploy.meng.xu
  resources:
  - configdeployments/status
  verbs:
  - get
